spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true
    change-log: db.changelog-master.xml
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    ROOT: ERROR