spring:
  r2dbc:
    url: r2dbc:h2:mem:///maindb;DB_CLOSE_DELAY=-1
    username: sa
    password: password

  liquibase:
    enabled: true
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    user: sa
    password: password
    change-log: classpath:db.changelog-master.xml
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    ROOT: ERROR