server:
  port: 8085

spring:
  data:
    mongodb:
      port: 0
      host: localhost
      database: books

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.5

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

#logging:
#  level:
#    ROOT: ERROR