spring:
  application:
    name: hw17
  profiles:
    active: h2

logging:
  level:
    root: INFO
    ru.shintar: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  shutdown: graceful

# --- H2  ---
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: db.changelog-master.xml

# --- PostgreSQL (docker/compose) ---
---
spring:
  config:
    activate:
      on-profile: pg
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:librarydb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: db.changelog-master.xml
