apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - { name: POSTGRES_DB, value: "librarydb" }
            - { name: POSTGRES_USER, value: "postgres" }
            - { name: POSTGRES_PASSWORD, value: "postgres" }
          ports:
            - { containerPort: 5432 }
          readinessProbe:
            exec: { command: ["sh","-c","pg_isready -U postgres -d librarydb"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["sh","-c","pg_isready -U postgres -d librarydb"] }
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - { name: pgdata, mountPath: /var/lib/postgresql/data }
      volumes:
        - name: pgdata
          emptyDir: {}
